---
- name: Installation de phpMyAdmin
  hosts: Servers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install phpMyAdmin
      apt:
        name: phpmyadmin
        state: present

